
# compiler flags
CXX             = g++ 
CXXFLAGS        = -g -O2 -Wno-deprecated -Wall -Wextra    \
                  -Wc++0x-compat -pedantic -ansi -Weffc++
CPPFLAGS        = -Isrc -I/usr/include                    \
                  -I/usr/include/python2.7
LIBFLAGS        =  -v -L/usr/lib -lpython2.7 -llapack
TEST_CXXFLAGS   =  $(CXXFLAGS)
TEST_CPPFLAGS   =  $(CPPFLAGS)
TEST_LIBFLAGS   =  $(LIBFLAGS) -lgtest
