
# compiler flags
CXX             = g++
CXXFLAGS        = -g -O2 -Wno-deprecated -Wall -Wextra    \
                  -Wc++0x-compat -pedantic -ansi -Weffc++
CPPFLAGS        = -Isrc -I/usr/include                    \
                  -I/usr/include/python2.7                \
                  -I/opt/acml4.4.0/gfortran32_mp/include
LIBFLAGS        = -L/usr/lib                              \
                  -lpython2.7                             \
                  -L/opt/acml4.4.0/gfortran32_mp/lib      \
                  -lacml_mp -lgfortran -lgomp -lrt -lm    
TEST_CXXFLAGS   =  $(CXXFLAGS)
TEST_CPPFLAGS   =  $(CPPFLAGS)
TEST_LIBFLAGS   =  $(LIBFLAGS) -lgtest
